In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import resample
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/content/LoanApprovalPrediction.csv')

In [3]:
df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2.0,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0.0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3.0,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2.0,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1.0,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [4]:
df.tail(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
588,LP002959,Female,Yes,1.0,Graduate,No,12000,0.0,496.0,360.0,1.0,Semiurban,Y
589,LP002960,Male,Yes,0.0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
590,LP002961,Male,Yes,1.0,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y
591,LP002964,Male,Yes,2.0,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
592,LP002974,Male,Yes,0.0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
593,LP002978,Female,No,0.0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
594,LP002979,Male,Yes,3.0,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
595,LP002983,Male,Yes,1.0,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
596,LP002984,Male,Yes,2.0,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
597,LP002990,Female,No,0.0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [5]:
df.describe()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,586.000000,598.000000,598.000000,577.000000,584.000000,549.000000
mean,0.755973,5292.252508,1631.499866,144.968804,341.917808,0.843352
std,1.007751,5807.265364,2953.315785,82.704182,65.205994,0.363800
min,0.000000,150.000000,0.000000,9.000000,12.000000,0.000000
25%,0.000000,2877.500000,0.000000,100.000000,360.000000,1.000000
50%,0.000000,3806.000000,1211.500000,127.000000,360.000000,1.000000
75%,1.750000,5746.000000,2324.000000,167.000000,360.000000,1.000000
max,3.000000,81000.000000,41667.000000,650.000000,480.000000,1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598 entries, 0 to 597
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            598 non-null    object
 1   Gender             598 non-null    object
 2   Married            598 non-null    object
 3   Dependents         586 non-null    float64
 4   Education          598 non-null    object
 5   Self_Employed      598 non-null    object
 6   ApplicantIncome    598 non-null    int64
 7   CoapplicantIncome  598 non-null    float64
 8   LoanAmount         577 non-null    float64
 9   Loan_Amount_Term   584 non-null    float64
 10  Credit_History     549 non-null    float64
 11  Property_Area      598 non-null    object
 12  Loan_Status        598 non-null    object
dtypes: float64(5), int64(1), object(7)
memory usage: 60.9+ KB

In [7]:
df = df.drop(['Loan_ID'], axis=1)

In [9]:
df.isnull().sum()

Gender                0
Married               0
Dependents           12
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

In [12]:
dependents_mean = df['Dependents'].mean()
loan_amount_mean = df['LoanAmount'].mean()
loan_amount_term_mean = df['Loan_Amount_Term'].mean()
credit_history_mean = df['Credit_History'].mean()

df['Dependents'].fillna(dependents_mean, inplace=True)
df['LoanAmount'].fillna(loan_amount_mean, inplace=True)
df['Loan_Amount_Term'].fillna(loan_amount_term_mean, inplace=True)
df['Credit_History'].fillna(credit_history_mean, inplace=True)

In [14]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0.0,Graduate,No,5849,0.0,144.968804,360.0,1.0,Urban,Y
1,Male,Yes,1.0,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,Male,No,0.0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
593,Female,No,0.0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural,Y
594,Male,Yes,3.0,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,Y
595,Male,Yes,1.0,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,Y
596,Male,Yes,2.0,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,Y
597,Female,No,0.0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N

In [15]:
df['Loan_Status'].value_counts()

Loan_Status
Y    411
N    187
Name: count, dtype: int64

In [49]:
df_majority = df[df['Loan_Status'] == 'Y']
df_minority = df[df['Loan_Status'] == 'N']

df_minority_upsampled = resample(df_minority,
                                replace = True,
                                n_samples = 411,
                                random_state = 123)

df_final = pd.concat([df_majority, df_minority_upsampled])

In [50]:
df_final['Loan_Status'].value_counts()

Loan_Status
Y    411
N    411
Name: count, dtype: int64

In [48]:
categorical_cols = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area']
numerical_cols = ['Dependents', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']

In [51]:
df_encoded = pd.get_dummies(df_final, columns=categorical_cols, drop_first=True)

df_encoded.head()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,0.0,5849,0.0,144.968804,360.0,1.0,Y,True,False,False,False,False,True
2,0.0,3000,0.0,66.000000,360.0,1.0,Y,True,True,False,True,False,True
3,0.0,2583,2358.0,120.000000,360.0,1.0,Y,True,True,True,False,False,True
4,0.0,6000,0.0,141.000000,360.0,1.0,Y,True,False,False,False,False,True
5,2.0,5417,4196.0,267.000000,360.0,1.0,Y,True,True,False,True,False,True

In [52]:
scaler = StandardScaler()
df_encoded[numerical_cols] = scaler.fit_transform(df_encoded[numerical_cols])

In [53]:
encoder = LabelEncoder()
df_encoded['Loan_Status'] = encoder.fit_transform(df_encoded['Loan_Status'])

In [54]:
df_encoded

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,-0.729446,0.052944,-0.502437,-0.053864,0.266118,0.580638,1,True,False,False,False,False,True
2,-0.729446,-0.376949,-0.502437,-0.950228,0.266118,0.580638,1,True,True,False,True,False,True
3,-0.729446,-0.439872,0.145158,-0.337281,0.266118,0.580638,1,True,True,True,False,False,True
4,-0.729446,0.075729,-0.502437,-0.098913,0.266118,0.580638,1,True,False,False,False,False,True
5,1.301861,-0.012242,0.649942,1.331295,0.266118,0.580638,1,True,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,-0.729446,0.830192,-0.502437,-0.757263,0.266118,0.580638,0,True,False,False,True,False,True
61,-0.729446,-0.435948,0.444787,0.173508,-2.546288,-1.821249,0,True,True,True,True,False,False
74,-0.729446,-0.263780,-0.502437,-0.416737,2.141055,0.580638,0,True,False,False,False,False,True
23,0.286207,-0.268759,0.300877,0.014595,0.266118,0.204386,0,True,True,False,True,True,False
126,-0.729446,0.087800,0.203106,0.366472,0.266118,0.204386,0,True,True,False,False,False,False

In [55]:
X = df_encoded.drop('Loan_Status', axis=1)
y = df_encoded['Loan_Status']

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
lr = LogisticRegression()
lr_model = lr.fit(X_train, y_train)

In [58]:
y_pred_lr = lr_model.predict(X_test)

In [59]:
print('Classification Report:\n', classification_report(y_test, y_pred_lr))
print('Accuracy Score:', accuracy_score(y_test, y_pred_lr))

Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.65      0.71        83
           1       0.69      0.80      0.75        82

    accuracy                           0.73       165
   macro avg       0.73      0.73      0.73       165
weighted avg       0.73      0.73      0.73       165

Accuracy Score: 0.7272727272727273

In [60]:
knn = KNeighborsClassifier()
knn_model = knn.fit(X_train, y_train)

In [61]:
y_pred_knn = knn_model.predict(X_test)

In [62]:
print('Classification Report:\n', classification_report(y_test, y_pred_knn))
print('Accuracy Score:', accuracy_score(y_test, y_pred_knn))

Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.70      0.73        83
           1       0.72      0.79      0.76        82

    accuracy                           0.75       165
   macro avg       0.75      0.75      0.74       165
weighted avg       0.75      0.75      0.74       165

Accuracy Score: 0.7454545454545455

In [63]:
rfc = RandomForestClassifier()
rfc_model = rfc.fit(X_train, y_train)

In [64]:
y_pred_rfc = rfc_model.predict(X_test)

In [65]:
print('Classification Report:\n', classification_report(y_test, y_pred_rfc))
print('Accuracy Score:', accuracy_score(y_test, y_pred_rfc))

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93        83
           1       0.94      0.91      0.93        82

    accuracy                           0.93       165
   macro avg       0.93      0.93      0.93       165
weighted avg       0.93      0.93      0.93       165

Accuracy Score: 0.9272727272727272